# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/selinux
  block:

    - name: CIS | Ensure AppArmor is installed
      become: true
      ansible.builtin.package:
        name:
          - 'python3-libapparmor'
          - 'python3-apparmor'
          - 'apparmor'
          - 'apparmor-utils'
        state: present

    - name: CIS | Ensure AppArmor is enabled in the bootloader configuration
      become: true
      ansible.builtin.template:
        src: 'etc/default/grub.d/60-apparmor.cfg.j2'
        dest: '/etc/default/grub.d/60-apparmor.cfg'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify:
        - AppArmor update grub

    # Flush any handlers that we might have called
    - name: Flush handlers
      ansible.builtin.meta:
        flush_handlers

  when:
    - ansible_os_family == 'Debian'

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_apparmor'
