# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: AppArmor update grub
  become: true
  ansible.builtin.command:
    cmd: "update-grub"
